### ISSUE TITLE
Learn Python in One Day By Jamie Chan

### ISSUE THREAD

**Issue by developedbysom** [AnandChowdhary/books#65]

**Comment by AnandChowdhary** [comment]
I can't believe I never thought of this... That only you should be able to create issues in your own repository.

**Comment by AnandChowdhary** [comment]
Fixed in [AnandChowdhary/books#1](https://github.com/AnandChowdhary/bookshelf-action/commit/65852a12fe2ff395c50526c6d8b73e917de9ad60)
